hard_tabs = true
tab_spaces = 8
max_width = 100
binop_separator = "Back"
brace_style = "PreferSameLine"
control_brace_style = "AlwaysSameLine"
format_strings = true
match_arm_leading_pipes = "Preserve"

